- name: install GPG package (Ubuntu)
  apt:
    name: gnupg
    state: present
  when: ansible_distribution == "Ubuntu"

- name: add elasticsearch apt repository (Ubuntu)
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
  when: ansible_distribution == "Ubuntu"
  become: yes

- name: add elasticsearch yum repository (CentOS)
  yum_repository:
    name: elasticsearch
    description: Elasticsearch repository
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
  when: ansible_distribution == "CentOS"
  become: yes

- name: install elasticsearch
  package:
    name: elasticsearch
    state: latest
  become: yes

- name: start elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: yes
  become: yes
