- name: install kibana (Ubuntu)
  apt:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: download kibana (CentOS)
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-8.4.3-x86_64.rpm
    dest: /tmp/kibana-8.4.3-x86_64.rpm
  when: ansible_distribution == "CentOS"

- name: install kibana (CentOS)
  yum:
    name: /tmp/kibana-8.4.3-x86_64.rpm
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: start kibana
  service:
    name: kibana
    state: restarted
